### ISSUE TITLE
initialize rails project

### ISSUE THREAD

**Issue by skamansam** [BizziQuest/QuestLists#1]
We need to initialize the project with the latest version of rails, using the API settings. See https://edgeguides.rubyonrails.org/api_app.html for how to do this. The project name should be the same as this repo's name. The resulting README should contain *at least* the project name and the description as it is currently in the README.

**Comment by KickButtowski80** [comment]
I am confused about making the project.
Is it project like a folder inside the repo?

**Comment by KickButtowski80** [comment]
> I am confused about making the project.
> Is it project like a folder inside the repo?

 I found this link [https://blog.jasonmeridth.com/posts/create-rails-application-in-current-directory/](url) which sloves my issue

**Comment by KickButtowski80** [comment]
I am confused 
I do not know what I need to do 
I thought the link is gonna be the answer, yet I cannot make new project by `rails new . --api `

**Comment by skamansam** [comment]
see documentation for the rails command line tools here: https://guides.rubyonrails.org/command_line.html . After initializing the app, add the git remote (this repo) by following the directions here: https://help.github.com/en/github/using-git/adding-a-remote

**Comment by skamansam** [comment]
also, it may be easier to init webpack with vue, using the `--webpack=vue` option for `rails new`

**Comment by skamansam** [comment]
It seems we need to not use the `--api` flag if we want to keep the frontend and backend together. We can work around it, but it may be easier for now, to skip this flag.

**Comment by KickButtowski80** [comment]
Even though I have already known all those commands , I went through the link found nothing new.  As you see in following pic, I added to repo  and beside there is not huge difference between `git remote add` vs `git clone` because I did` git clone`

![init-issue](https://user-images.githubusercontent.com/18540566/71567251-6bb6c580-2a72-11ea-9c5c-79e6be408446.jpg)

 
I feel you want me to make project  QuestLists inside  BizziQuest folder?

**Comment by skamansam** [comment]
You mentioned creating a Rails app in the current directory. This is probably not the best practice and is more difficult than adding a git remote. You can put the git repo wherever you want, but the rails app should be the top directory in the repo. All you really need to do is issue the following commands:

```
gem install rails && rails new --webpack=vue quest_lists
cd quest_lists
git add remote origin https://github.com/BizziQuest/QuestLists.git
git checkout -b "1-init-rails-project"
git add .
git commit -m "initialized rails app"
git push origin
```

**Comment by KickButtowski80** [comment]
first, I realized I had a rails project inside my folder so when I deleted them I was able to create new rails app.
I was able to create rails app by running` rails new quest_lists --webpack=vue `
and `git remote add origin https://github.com/BizziQuest/QuestLists.git`
I commit everything and git push origin as well. 
FYI, I never created any project this way :)
